export const categories = [
   "backgrounds",
   "fashion",
   "nature",
   "science",
   "education",
   "feelings",
   "health",
   "people",
   "religion",
   "places",
   "animals",
   "industry",
   "computer",
   "food",
   "sports",
   "transportation",
   "travel",
   "buildings",
   "business",
   "music",
];

export const filterData = {
   orientation: ["all", "horizontal", "vertical"],
   image_type: ["all", "photo", "illustration", "vector"],
   order: ["popular", "latest"],
   colors: [
      "red",
      "orange",
      "yellow",
      "green",
      "turquoise",
      "blue",
      "pink",
      "white",
      "gray",
      "black",
      "brown",
   ],
};
